training:
  batch_size: 64
  transform: "identity"
  device: "cuda"
  n_epochs: 100
  learning_rate: 0.0002

model_specifics:
  n_channel_scaling_factor: 64 
  lambda_gp: 10
  mode_z: "uniform"
  z_size: 100
  n_critic_iterations: 5